name: Upgrade Charts

on:
  # workaround to make missing workflow appear in GitHub actions
  push:
    branches:
      - github-actions-workaround
  pull_request:
    paths:
      - 'charts/item-relationship-service/**'
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v2

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.9.3

      - name: Add repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add minio https://charts.min.io/
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add irs https://eclipse-tractusx.github.io/item-relationship-service

      - name: Run helm install
        # Install latest released item-relationship-service version
        run: |
          helm install irs irs/item-relationship-service 

      - name: Run helm upgrade
        # Upgrade the installed item-relationship-service version with the locally available charts
        run: |
          helm dependency update charts/item-relationship-service
          helm upgrade irs charts/item-relationship-service 
