name: "Publish OpenAPI to Swaggerhub"

on:
  # workaround to make missing workflow appear in GitHub actions
  push:
    branches:
      - github-actions-workaround
  workflow_call:
    inputs:
      version:
        required: true
        description: Version that will be published to Swaggerhub
        type: string

jobs:
  swagger-api:
    runs-on: ubuntu-latest
    env:
      SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
      SWAGGERHUB_USER: ${{ secrets.SWAGGERHUB_USER }}
      DOWNSTREAM_VERSION: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install Swagger CLI
        run: |
          npm i -g swaggerhub-cli

      # create API, will fail if exists
      - name: Create API
        continue-on-error: true
        run: |
          swaggerhub api:create ${{ env.SWAGGERHUB_USER }}/item-relationship-service/${{ env.DOWNSTREAM_VERSION }} -f docs/src/api/irs-api.yaml --visibility=public --published=unpublish

      # Post the API to SwaggerHub as "unpublished", because published APIs cannot be overwritten
      - name: Publish API Specs to SwaggerHub
        run: |
          if [[ ${{ env.DOWNSTREAM_VERSION }} != *-SNAPSHOT ]]; then
            echo "[INFO] - no snapshot, will set the API to 'published'";
            swaggerhub api:update ${{ env.SWAGGERHUB_USER }}/item-relationship-service/${{ env.DOWNSTREAM_VERSION }} -f docs/src/api/irs-api.yaml --visibility=public --published=publish
            swaggerhub api:setdefault ${{ env.SWAGGERHUB_USER }}/item-relationship-service/${{ env.DOWNSTREAM_VERSION }}
          else
            echo "[INFO] - snapshot, will set the API to 'unpublished'";
            swaggerhub api:update ${{ env.SWAGGERHUB_USER }}/item-relationship-service/${{ env.DOWNSTREAM_VERSION }} -f docs/src/api/irs-api.yaml --visibility=public --published=unpublish
          fi
